mysite/log_pay/urls.py
from django.urls import path
from log_pay.views import *
from . import views
app_name = 'log_pay'
urlpatterns = [
    path('accounts/registration/', views.registration, name='registration'),
    path('index/', views.index, name='index'),
    path('', views.mission, name='mission'),
    path('types/<int:types_id>/', views.types, name='types'),
    path('eyJ1Ijoic2FkcmlrIiwiYSI6ImNrZ3ZhNWhrZDBpbXgycXJ5Z2cwNmFzZTcifQ.cxbz_15TzOfpWeFafy3sUQ/', views.one, name='one'),
]

mysite/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('log_pay.urls')),
    path('admin/', admin.site.urls),
]

mysite/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{{ form.media }}
    <title>{% block title %}{% endblock %}</title>
      {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- ICO -->
    <link type='image/ico' rel='shortcut icon' href="{% static '/images/gaun_15.png' %}" />
    <link type='image/ico' rel='icon' href="{% static '/images/gaun_15.png' %}" />
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static '/polls/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
    <link rel="stylesheet" href="{% static '/polls/plugins/bootstrap/css/bootstrap.min.css' %}">
<!-- flag-icon-css -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/css/flag-icon.min.css">
  
  <link rel="stylesheet" href="{% static '/polls/dist/css/ionicons.min.css' %}">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static '/polls/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static '/polls/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static '/polls/plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static '/polls/dist/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static '/polls/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static '/polls/plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static '/polls/plugins/summernote/summernote-bs4.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="{% static '/polls/dist/css/face.css' %}" rel="stylesheet">
  <!-- My style -->
  <link href="{% static '/polls/my/css/my.css' %}" rel="stylesheet">
</head>
{% block css %}
{% endblock %}

<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Navbar -->

  {% include 'base/navbar.html' %}
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <img src="{% static '/images/gaun_15.png' %}" 
		   alt="AdminLTE Logo" 
		   class="brand-image img-circle elevation-3"
           style="opacity: .9">
      <span class="brand-text font-weight-light">
	  <b>pro<strong class="text-warning">ARHIV</strong></b>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->

				{% include 'base/sidebar.html' %}
       </ul>   
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
	{% block content %}
		{% block page %}
		{% endblock page %}
	{% endblock content %}
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
{% include 'base/footer.html' %}
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
<!-- jQuery -->
<script src="{% static '/polls/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static '/polls/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static '/polls/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static '/polls/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static '/polls/plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static '/polls/plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static '/polls/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static '/polls/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static '/polls/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static '/polls/plugins/moment/moment.min.js' %}"></script>
<script src="{% static '/polls/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static '/polls/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static '/polls/plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static '/polls/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static '/polls/dist/js/adminlte.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static '/polls/dist/js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static '/polls/dist/js/demo.js' %}"></script>
<script src="{% static '/polls/plugins/popper.min.js' %}"></script>
<script>
$(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();   
});
</script>
{% block scripts %}
{% endblock %}
</body>
</html>

mysite/templates/base/error_404.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Страница не найдена{% endblock %}
{% block css %}
  <script src="{% static '/polls/plotly/js/plotly.js' %}"></script>
{% endblock %}

	{% block content %}
    {% block page %}
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>404 Error Page</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'polls:index' %}">Главная страница</a></li>
              <li class="breadcrumb-item active">Страница не найдена</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="error-page">
        <h2 class="headline text-warning"> 404</h2>

        <div class="error-content">
          <h3><i class="fas fa-exclamation-triangle text-warning"></i> Oops! Page not found.</h3>

          <p>
            We could not find the page you were looking for.
            Meanwhile, you may <a href="{% url 'polls:index' %}">return to dashboard</a> or try using the search form.
          </p>

          <form class="search-form">
            <div class="input-group">
              <input type="text" name="search" class="form-control" placeholder="Search">

              <div class="input-group-append">
                <button type="submit" name="submit" class="btn btn-warning"><i class="fas fa-search"></i>
                </button>
              </div>
            </div>
            <!-- /.input-group -->
          </form>
        </div>
        <!-- /.error-content -->
      </div>
      <!-- /.error-page -->
    </section>
    <!-- /.content -->
  {% endblock page %}
{% endblock content %}
{% block scripts %}
	<!-- <script src="{% static '/polls/sat/js/three.min.js' %}"></script>
	<script src="{% static '/polls/sat/js/Detector.js' %}"></script>		
	<script src="{% static '/polls/sat/js/TrackballControls.js' %}"></script>		
	<script src="{% static '/polls/sat/js/earth.js' %}"></script>   -->
{% endblock %}

mysite/templates/base/footer.html
    <strong>Copyright &copy; 2020 <a href="#">MozhaykaTeam</a></strong>
    Все права защищены.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 0.0.1-pre
    </div>

mysite/templates/base/navbar.html
{% block navbar %}

  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
<ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Главная страница</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Справка</a>
      </li>
    </ul>

<!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="../../dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="../../dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="../../dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <!-- Language Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="flag-icon flag-icon-ru"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right p-0">
		<a href="#" class="dropdown-item active">
            <i class="flag-icon flag-icon-ru mr-2"></i> Русский
          </a>
          <a href="#" class="dropdown-item">
            <i class="flag-icon flag-icon-us mr-2"></i> English
          </a>
          <a href="#" class="dropdown-item">
            <i class="flag-icon flag-icon-de mr-2"></i> German
          </a>
          <a href="#" class="dropdown-item">
            <i class="flag-icon flag-icon-fr mr-2"></i> French
          </a>
          <a href="#" class="dropdown-item">
            <i class="flag-icon flag-icon-es mr-2"></i> Spanish
          </a>
        </div>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->
{% endblock %}

mysite/templates/base/sidebar.html
{% block sidebar %}
			<li class="nav-item has-treeview">
			<a href="{% url 'log_pay:index' %}"  class="nav-link active">
              <i class="nav-icon fas fa-globe"></i>
              <p>
                Архив
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
			{% for i in types %}
			<li class="nav-item">
                <a href="{% url 'log_pay:types' i.id%}" class="nav-link">
                  <i class="nav-icon far fa-circle"></i>
                  <p> {{i.name}}
				   <i class="fas fa-angle-left right"></i>
				   </p>
				</a>
			</li>
			{% endfor %}
			</ul>
          </li>
          <li class="nav-item">
            <a href="{% url 'log_pay:mission' %}" class="nav-link">
              <i class="nav-icon fab fa-superpowers"></i>
              <p>
                Задачи
              </p>
            </a>
          </li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fa fa-share-alt"></i>
              <p>
                Архивация
                <span class="right badge badge-danger">Новинка</span>
              </p>
            </a>
          </li>
          <li class="nav-header">СПРАВКА</li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-circle text-danger"></i>
              <p class="text">Настройка аккаунта</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-circle text-warning"></i>
              <p>Анализ документов</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-circle text-info"></i>
              <p>Как это работает?</p>
            </a>
          </li>
        </ul>
{% endblock %}