mysite/log_pay/urls.py
from django.urls import path
from log_pay.views import *
from . import views
app_name = 'log_pay'
urlpatterns = [
    path('accounts/registration/', views.registration, name='registration'),
    path('index/', views.index, name='index'),
    path('', views.mission, name='mission'),
    path('types/<int:types_id>/', views.types, name='types'),
    path('eyJ1Ijoic2FkcmlrIiwiYSI6ImNrZ3ZhNWhrZDBpbXgycXJ5Z2cwNmFzZTcifQ.cxbz_15TzOfpWeFafy3sUQ/', views.one, name='one'),
]

mysite/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('log_pay.urls')),
    path('admin/', admin.site.urls),
]

mysite/log_pay/models.py
#-*- coding: utf-8 -*-
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.contrib.auth.models import AbstractUser
import datetime
from django.utils import timezone
from django.conf import settings
from datetime import datetime

# Create your models here.
private_storage = FileSystemStorage(location=settings.PRIVATE_STORAGE_ROOT)
media_storage = FileSystemStorage(location=settings.MEDIA_ROOT)

#Class's doc
class Type(models.Model):
    name = models.CharField(max_length = 128, verbose_name='Название класса')
    example = models.FileField('Образец', storage=private_storage)
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Класс'
        verbose_name_plural = 'Классы'

class Doc(models.Model):
    name = models.CharField(max_length = 128, verbose_name='Название документа')
    file = models.CharField(max_length = 580, verbose_name='Ссылка документа')
    type = models.ForeignKey(Type, on_delete=models.CASCADE, null=True, verbose_name='Класс документа', related_name='doc')
    nomber = models.CharField(max_length = 128, verbose_name='Номер документа')
    year = models.IntegerField(default=0, verbose_name='Год')
    adress = models.CharField(max_length = 128, verbose_name='Адрес')
    owner = models.CharField(max_length = 128, verbose_name='Владелец')
    lat = models.FloatField(default=0, verbose_name='Широта, °')
    long = models.FloatField(default=0, verbose_name='Долгота, °')
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Документ'
        verbose_name_plural = 'Документы'

mysite/log_pay/views.py
#-*- coding: utf-8 -*-
from django.shortcuts import render
from django.contrib.admin.models import LogEntry
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required
import datetime
from django.core.serializers import serialize
from .forms import *
from django.contrib.auth.models import User

from plotly.offline import plot
import pandas as pd
import plotly.graph_objects as go
import plotly.graph_objects as go
import plotly.express as px
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve, roc_auc_score
import xlrd
import time
import telebot
from telebot import types
from absl import logging

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image, ImageOps
from scipy.spatial import cKDTree
from skimage.feature import plot_matches
from skimage.measure import ransac
from skimage.transform import AffineTransform
from six import BytesIO

import tensorflow as tf

import tensorflow_hub as hub
from six.moves.urllib.request import urlopen
import urllib.request
import skimage

import os
import json
from datetime import datetime
import time
import csv
import codecs
import glob
from itertools import accumulate
from os import walk


def yandex_coor(adress):
    client = Client("your-api-key")
    coordinates = client.coordinates(adress)
    return coordinates

def run_delf(image):
  np_image = np.array(image)
  float_image = tf.image.convert_image_dtype(np_image, tf.float32)

  return delf(
      image=float_image,
      score_threshold=tf.constant(100.0),
      image_scales=tf.constant([0.25, 0.3536, 0.5, 0.7071, 1.0, 1.4142, 2.0]),
      max_feature_num=tf.constant(1000))
def match_images(data, result2):
    distance_threshold = 0.6

    num_features_1 = len(data['locations'])
    num_features_2 = result2['locations'].shape[0]

    d1_tree = cKDTree(data['descriptors'])
    _, indices = d1_tree.query(
        result2['descriptors'],
        distance_upper_bound=distance_threshold)

    locations_2_to_use = np.array([
        result2['locations'][i,]
        for i in range(num_features_2)
        if indices[i] != num_features_1
    ])
    locations_1_to_use = np.array([
        data['locations'][indices[i]]
        for i in range(num_features_2)
        if indices[i] != num_features_1
    ])

    _, inliers = ransac(
        (locations_1_to_use, locations_2_to_use),
        AffineTransform,
        min_samples=3,
        residual_threshold=20,
        max_trials=1000)
    return {"inliers": sum(inliers)}
    
    
    
def prognoz(path_im_test, name_test, list_f, destfolder, result_path):
    delf = hub.load('model').signatures['default']
    result1 = run_delf(Image.open(path_im_test+name_test))
    inliers_counts = {}
    inliers_counts['name'] = name_test
    inliers_rez = []
    for i in list_f:
        j = i.split('.json')[0]
        with open(destfolder+i, 'r') as fp:
            data = json.load(fp)
        try:
            result = match_images(data, result1)
            inliers_rez.append({"index": j, "inliers": int(result['inliers'])})
        except:
            pass
    top_match = sorted(inliers_rez, key=lambda k: k['inliers'], reverse=True)[0]
    inliers_counts['index'] = top_match['index']
    inliers_counts['inliers'] = top_match['inliers']
    with open(result_path+name_test.split('.jpg')[0]+'.json', 'w') as fp:
        json.dump(inliers_counts, fp)

def registration(request):
    if request.POST:
        username = request.POST['name']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        if password == password2:
            new_user = User.objects.create_user(username, email, password)
            new_user.save()
        return HttpResponseRedirect('/accounts/login/')
    content = {}
    return render(request, 'registration/registration.html', content)   
@login_required
def index(request):
    types = Type.objects.all()
    content = {'types':types}   
    return render(request, 'log_pay/index.html', content)
@login_required
def mission(request):
    types = Type.objects.all()
    if 'new_type' in request.POST:
        new_type = Type(name=request.POST['name'], example = request.POST['input_file_type'])
        new_type.save()
        return HttpResponseRedirect('/')
    content = {'types':types}            
    return render(request, 'log_pay/missions.html', content)  

@login_required
def types(request, types_id):
    df = pd.read_excel('11.xlsx')
    types = Type.objects.all()
    type1 = Type.objects.get(id=types_id)
    
    df=(df.loc[df['Тип документа'] == type1.name])
    names = df.values.tolist() 
    
    fig_al =  go.Figure()
    scatter = go.Densitymapbox(lat=df['широта '], lon=df['долгота'], z=df['Дата'],
                                 radius=10)
    fig_al.add_trace(scatter)
    
    fig_al.update_layout(
        autosize=True,
        width=1000,
        height=700,
        margin=dict(
            l=0,
            r=0,
            b=0,
            t=0,
            pad=2
        ),
        mapbox_style="stamen-terrain",
        mapbox_center_lon=57,
        mapbox_center_lat=30
    )

    fig_al.update_yaxes(automargin=True)
    plt_div_al = plot(fig_al, output_type='div', include_plotlyjs = True)
    
    content = {'types':types, 'type':type1, 'names':names, 'plt_div_al':plt_div_al}            
    return render(request, 'log_pay/types.html', content)  
@login_required
def history(request):
    content = {}            
    return render(request, 'log_pay/history.html', content)  
def one(request):
    types = Type.objects.all()
    mapbox_access_token = ""
    fig = go.Figure(go.Scattermapbox(
            lat=['55.601996'],
            lon=['37.622614'],
            mode='markers',
            marker=go.scattermapbox.Marker(
                size=19
            ),
            text=["н.д."],
        ))

    fig.update_layout(
        autosize=True,
        hovermode='closest',
        mapbox=dict(
            accesstoken=mapbox_access_token,
            bearing=0,
            center=dict(
                lat=55.6,
                lon=37.6
            ),
            pitch=0,
            zoom=7
        ),
        width=1200, height=600
    )
    fig.update_yaxes(automargin=True)
    plt_fig = plot(fig, output_type='div', include_plotlyjs = True)
    content = {'plt_fig':plt_fig, 'types':types}   
    return render(request, 'log_pay/one.html', content)  

 #Add URL page
@login_required
def add_source(request):
    if request.POST:
        if 'http' in str(request.POST['url']):
            URL(url=request.POST['url']).save()
        if 'http' in str(request.POST['url2']):
            URL(url=request.POST['url2']).save()
        if 'http' in str(request.POST['url3']):
            URL(url=request.POST['url3']).save()
        if 'http' in str(request.POST['url4']):
            URL(url=request.POST['url4']).save()
        if 'html' in str(request.POST['input_file']):
            HTML(name=str(request.POST['input_file']), file=request.POST['input_file']).save()
        return HttpResponseRedirect('/mission/')
    content = {}
    return render(request, 'log_pay/add_source.html', content) 
    

mysite/templates/log_pay/history.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}История{% endblock %}
{% block css %}
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static '/polls/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static '/polls/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
{% endblock %}

{% block content %}
    {% block page %}
<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>История запросов</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
           <div class="timeline timeline-inverse">
                      <!-- timeline time label -->
                      <div class="time-label">
                        <span class="bg-danger">
                          29 окт. 2020
                        </span>
                      </div>
                      <!-- /.timeline-label -->
                      <!-- timeline item -->
                      <div>

                        <i class="fas fa-envelope bg-primary"></i>

                        <div class="timeline-item">
                          <span class="time"><i class="far fa-clock"></i> 1 мин. назад</span>

                          <h3 class="timeline-header"><a href="#">User</a> выполнил запрос</h3>

                          <div class="timeline-body">
                            Telegram
                          </div>
                          <div class="timeline-footer">
                            <a href="{% url 'log_pay:one' %}" class="btn btn-primary btn-sm">Открыть ссылку</a>
                            <a href="#" class="btn btn-danger btn-sm">Удалить</a>
                          </div>
                        </div>
                      </div>
                      <!-- END timeline item -->
                      <!-- timeline item -->
                    
                      <div class="time-label">
                        <span class="bg-success">
                          28 окт. 2020
                        </span>
                      </div>
                      <!-- /.timeline-label -->
                      <!-- timeline item -->
                      <div>
                        <i class="fas fa-camera bg-purple"></i>

                        <div class="timeline-item">
                          <span class="time"><i class="far fa-clock"></i> 1 день назад</span>

                          <h3 class="timeline-header"><a href="#">User</a> добавил новые изображения</h3>

                          <div class="timeline-body">
                            <img src="{% static '/images/1.jpg' %}" alt="...">
                            <img src="{% static '/images/2.jpg' %}" alt="...">
                            <img src="{% static '/images/3.jpg' %}" alt="...">
                            <img src="{% static '/images/4.jpg' %}" alt="...">
                          </div>
                        </div>
                      </div>
                      <!-- END timeline item -->
                      <div>
                        <i class="far fa-clock bg-gray"></i>
                      </div>
                    </div>
                  
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
    {% endblock page %}
{% endblock content %}
{% block scripts %}
<!-- DataTables -->
<script src="{% static '/polls/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static '/polls/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static '/polls/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static '/polls/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
	$("#example2").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
		$("#example3").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
	$("#example4").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
  });
</script>
{% endblock %}

mysite/templates/log_pay/index.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Профиль{% endblock %}
{% block css %}
<style>body { margin: 0;}<style/>
<style>canvas { width: 100%; height: 100% }</style>
<script src="{% static '/polls/plotly/js/plotly.js' %}"></script>
<script src="{% static '/polls/my/js/three.min.js' %}"></script>
{% endblock %}

{% block content %}
    {% block page %}
	<!-- Content Header (Page header) -->
<div class="content-header">
	<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Профиль</h1>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content-header -->
	<!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills">
                  <li class="nav-item"><a class="nav-link active" href="#activity" data-toggle="tab">Карта запросов</a></li>
					<li class="nav-item"><a class="nav-link" href="#settings" data-toggle="tab">Все документы</a></li>

                </ul>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content">
                  <div class="active tab-pane" id="activity">
				  <div class="row">
                <!-- accepted payments column -->
                
				</div>
                    <!-- Post -->
                    <div class="post">
                      <div class="user-block">
                        <img class="img-circle img-bordered-sm" src="{% static '/images/user-100.png' %}" alt="user image">
                        <span class="username">
                          <a href="#">User</a>
                          <a href="#" class="float-right btn-tool"><i class="fas fa-times"></i></a>
                        </span>
                        <span class="description"> Последний запрос - 21:30 29.10.2020 г.</span>
                      </div>
                      <!-- /.user-block -->
				<div class="col-12">
                  <p class="lead">Все запросы</p>
				                   
                  {% autoescape off %}
				  {{ plt_div }}
				  {% endautoescape %}
				</div>

                      <p>
                        <a href="#" class="link-black text-sm mr-2"><i class="fas fa-share mr-1"></i> Share</a>
                        <a href="#" class="link-black text-sm"><i class="far fa-thumbs-up mr-1"></i> Like</a>
                        <span class="float-right">
                          <a href="#" class="link-black text-sm">
                            <i class="far fa-comments mr-1"></i> Комментарии
                          </a>
                        </span>
                      </p>

                      <input class="form-control form-control-sm" type="text" placeholder="Текст...">
                    </div>
                    <!-- /.post -->

                    <!-- Post -->
               
                  </div>
                  <!-- /.tab-pane -->
                

                  <div class="tab-pane" id="settings">
				  <div class="col-12">
                  <p class="lead"></p>
				                   
                  {% autoescape off %}
				  {{ plt_fig }}
				  {% endautoescape %}
				</div>
                   </div>
                  <!-- /.tab-pane -->
				 
                </div>
                <!-- /.tab-content -->
              </div><!-- /.card-body -->
            </div>
            <!-- /.nav-tabs-custom -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
	</div>
    <!-- /.content -->
    {% endblock page %}
{% endblock content %}
{% block scripts %}
{% endblock %}

mysite/templates/log_pay/missions.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Задачи{% endblock %}
{% block css %}
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static '/polls/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static '/polls/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
{% endblock %}

{% block content %}
    {% block page %}
	    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Задачи</h1>
          </div>
          <div class="col-sm-6">
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Задачи</h3>

          <div class="card-tools">
          </div>
        </div>
        <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 1%">
                          #
                      </th>
                      <th style="width: 20%">
                          Тип задачи
                      </th>
                      <th style="width: 30%">
                          Задача
                      </th>
                      <th style="width: 20%">
                      </th>
                  </tr>
              </thead>
              <tbody>
                  <tr>
                      <td>
                          1
                      </td>
                      <td>
                          <a>
                              Добавление класса документа
                          </a>
                          <br/>
                          <small>
                              Всего классов {{types|length}}
                          </small>
                      </td>
                      <td>
						<p>Определение нового класса документов.</p>
						Изменился формат документа или появился новый.
                      </td>
                      <td class="project-actions text-right">
                          <button type="button" class="btn btn-primary"  class="btn btn-info btn-sm" data-toggle="modal" data-target="#modal-lg">
                              <i class="fas fa-pencil-alt">
                              </i>
                              Настроить
                          </button>
                      </td>
                  </tr>
				   <tr>
                      <td>
                          2
                      </td>
                      <td>
                          <a>
                              Анализ и классификация документов
                          </a>
                          <br/>
                          <small>
                              Закончено {{custom_request.date}}
                          </small>
                      </td>
                      <td>
						Добавление электронных документов для классификации и выявление сущностей (NER).
                      </td>
                      <td class="project-actions text-right">
                          <button type="button" class="btn btn-primary"  class="btn btn-info btn-sm" data-toggle="modal" data-target="#modal-lg1">
                              <i class="fas fa-pencil-alt">
                              </i>
                              Настроить
                          </button>
                      </td>
                  </tr>
                   </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  <div class="modal fade" id="modal-lg">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Новый класс</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
			<form method="post" novalidate id="quickForm_type"> {% csrf_token %}
			<div class="row">
                    <div class="col-sm-12">
                      <!-- text input -->
                      <div class="form-group">
                        <label>Наименование класса</label>
                    <input type="text" name="name" class="form-control" id="id_name" maxlength="128" placeholder="Наименование">
                      </div>
                    </div>
                  </div>
              <div class="row">
                    <div class="col-sm-12">
					<label for="InputFileType">Добавить файл-образец</label>
					  <div class="form-group">
                    
      <input type="file"  name="input_file_type" id="InputFileType">
                    </div>
                    </div>
					</div>
					
            </div>
            <div class="modal-footer justify-content-between">
			  <button type="submit" name="new_type" class="btn btn-primary"><i class="fa fa-search" aria-hidden="true"></i> Добавить</button>
            </div>
			</form>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>
      <!-- /.modal -->
	   <div class="modal fade" id="modal-lg1">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Документы для обработки</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
			<form method="post" novalidate id="quickForm"> {% csrf_token %}
				 
  <div class="form-group">
      <input type="file" multiple name="input_file" id="InputFile">
  </div>

            </div>
            <div class="modal-footer justify-content-between">
			  <button type="submit" name="add_files" class="btn btn-primary"><i class="fa fa-search" aria-hidden="true"></i> Оценить</button>
            </div>
			</form>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>
      <!-- /.modal -->
    {% endblock page %}
{% endblock content %}
{% block scripts %}
<!-- DataTables -->
<script src="{% static '/polls/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static '/polls/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static '/polls/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static '/polls/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
	$("#example2").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
		$("#example3").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
	$("#example4").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
  });
</script>
{% endblock %}

mysite/templates/log_pay/one.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Класс{% endblock %}
{% block css %}
<style>body { margin: 0;}<style/>
<style>canvas { width: 100%; height: 100% }</style>
<script src="{% static '/polls/plotly/js/plotly.js' %}"></script>
<script src="{% static '/polls/my/js/three.min.js' %}"></script>
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static '/polls/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static '/polls/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
{% endblock %}

{% block content %}
    {% block page %}
	<!-- Content Header (Page header) -->
<div class="content-header">
	<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Класс "Разрешение на ввод в эксплуатацию"</h1>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content-header -->
	<!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills">
				<li class="nav-item"><a class="nav-link active" href="#docs" data-toggle="tab">Все документы</a></li>
                  <li class="nav-item"><a class="nav-link" href="#activity" data-toggle="tab">Карта запросов</a></li>
					

                </ul>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content">
				<div class="active tab-pane" id="docs">
				  <div class="col-12">
                  <p class="lead"></p>
				    <div class="card">
            <div class="card-header">
              <h3 class="card-title">Результаты распознанных документов</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Номер</th>
                  <th>Год</th>
                  <th>Адрес</th>
                  <th>Владелец</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                  <td>RU77217540</td>
                  <td>-</td>
                  <td>ул. Дорожная, д. 7</td>
                  <td>OOO.ГПК-Строй</td>
                </tr>
                </tbody>
                <tfoot>
                <tr>
                  <th>Номер</th>
                  <th>Год</th>
                  <th>Адрес</th>
                  <th>Владелец</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
				</div>
                   </div>
                  <!-- /.tab-pane -->
                  <div class="tab-pane" id="activity">
				  <div class="row">
                <!-- accepted payments column -->
                <div class="col-12">
				                   
                  {% autoescape off %}
				  {{ plt_fig }}
				  {% endautoescape %}
				</div>
				</div>
                    <!-- Post -->
       
                    <!-- Post -->
               
                  </div>
                  <!-- /.tab-pane -->
                

                  
				 
                </div>
                <!-- /.tab-content -->
              </div><!-- /.card-body -->
            </div>
            <!-- /.nav-tabs-custom -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
	</div>
    <!-- /.content -->
    {% endblock page %}
{% endblock content %}
{% block scripts %}
<!-- DataTables -->
<script src="{% static '/polls/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static '/polls/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static '/polls/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static '/polls/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
	$("#example2").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
		$("#example3").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
	$("#example4").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
  });
</script>
{% endblock %}